[2022-10-27T13:10:39.241+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tutorial.templated scheduled__2019-06-21T00:00:00+00:00 [queued]>
[2022-10-27T13:10:39.270+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tutorial.templated scheduled__2019-06-21T00:00:00+00:00 [queued]>
[2022-10-27T13:10:39.271+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T13:10:39.271+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-10-27T13:10:39.271+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-27T13:10:39.438+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): templated> on 2019-06-21 00:00:00+00:00
[2022-10-27T13:10:39.450+0000] {standard_task_runner.py:55} INFO - Started process 15806 to run task
[2022-10-27T13:10:39.455+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'templated', 'scheduled__2019-06-21T00:00:00+00:00', '--job-id', '4544', '--raw', '--subdir', 'DAGS_FOLDER/tuto.py', '--cfg-path', '/tmp/tmp56t2pgc8']
[2022-10-27T13:10:39.459+0000] {standard_task_runner.py:83} INFO - Job 4544: Subtask templated
[2022-10-27T13:10:39.484+0000] {logging_mixin.py:120} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2022-10-27T13:10:39.562+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-27T13:10:39.566+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 15806. PIDs of all processes in the group: [15806]
[2022-10-27T13:10:39.567+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 15806
[2022-10-27T13:10:39.583+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=15806, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='13:10:39') (15806) terminated with exit code Negsignal.SIGTERM
[2022-10-27T13:10:39.584+0000] {local_task_job.py:164} INFO - Task exited with return code 143
[2022-10-27T13:10:39.613+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-27T13:10:42.335+0000] {local_task_job.py:87} ERROR - Received SIGTERM. Terminating subprocesses
[2022-10-27T13:10:42.336+0000] {local_task_job.py:164} INFO - Task exited with return code 143
